califtecnologia:
    path:     /
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:index" }

califtecnologia_show:
    path:     /{id}/show
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:show" }

califtecnologia_new:
    path:     /new
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:new" }

califtecnologia_create:
    path:     /create
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:create" }
    methods:  POST

califtecnologia_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:edit" }

califtecnologia_update:
    path:     /{id}/update
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:update" }
    methods:  [POST, PUT]

califtecnologia_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionHabilidadesBundle:Califtecnologia:delete" }
    methods:  [POST, DELETE]
