gh_admin_index:
    path:     /admin/index/
    defaults: { _controller: GestionHabilidadesBundle:Administrador:index }

gh_profesional_agregar:
    path:   /profesional/agregar/
    defaults: { _controller: GestionHabilidadesBundle:Profesional:agregar }

gh_profesional_crear:
    path:   /profesional/crear/
    defaults: { _controller: GestionHabilidadesBundle:Profesional:crear }
    methods: POST

gh_proyecto_agregar:
    path:   /proyecto/agregar/
    defaults: { _controller: GestionHabilidadesBundle:Proyecto:agregar }

gh_proyecto_crear:
    path:   /proyecto/crear/
    defaults: { _controller: GestionHabilidadesBundle:Proyecto:crear }
    methods: POST