<?php

namespace GestionHabilidadesBundle\Entity;

/**
 * CaliftecnologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaliftecnologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
