<?php

namespace GestionHabilidadesBundle\Entity;

/**
 * CalifcompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalifcompetenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
