<?php

namespace GestionHabilidadesBundle\Entity;

/**
 * CompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
