<?php

namespace GestionHabilidadesBundle\Entity;

/**
 * RequeridoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeridoRepository extends \Doctrine\ORM\EntityRepository
{
}
