<?php

namespace GestionHabilidadesBundle\Entity;

/**
 * TecnologiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TecnologiaRepository extends \Doctrine\ORM\EntityRepository
{
}
